"""Package settings and defaults."""

### Constants and Configurations
# === Global variables and default values (initialized as empty) ===
DEFAULT_AI_METHOD = ""
ALL_AI_METHODS = []
GEMINI_API_KEY = ""
HUGGINGFACE_API_KEY = ""
GEMINI_DEFAULT_MODEL = ""
REPORT_REFINE_METHOD = ""
QUALITY_MIN_CHARS = 50
QUALITY_UNIQUE_CHAR_RATIO_MIN = 0.1
QUALITY_REPEAT_CHAR_RATIO_MAX = 0.12
QUALITY_VN_CHAR_RATIO_MIN = 0.03
QUALITY_ALNUM_RATIO_MIN = 0.4
QUALITY_SYMBOL_RATIO_MAX = 0.5
QUALITY_EMPTY_LINE_RATIO_MAX = 0.6
QUALITY_MATH_DENSITY_THRESHOLD = 0.05
QUALITY_LENGTH_RATIO_LOW = 0.3
QUALITY_LENGTH_RATIO_MEDIUM = 0.5
QUALITY_LENGTH_RATIO_HIGH = 0.7

DEFAULT_OCR_METHOD = "ocrspace"
ALL_OCR_METHODS = ["ocrspace", "tesseract", "paddleocr"]
OCRSPACE_API_KEY = ""
OCRSPACE_API_URL = "https://api.ocr.space/parse/image"

CANVAS_LMS_API_URL = ""
CANVAS_LMS_API_KEY = ""
CANVAS_LMS_COURSE_ID = ""

# Default course code used in config path when none is provided.
DEFAULT_COURSE_CODE = "mat3500"

MIDTERM_DATE = ""

EXAM_TYPE="" # 'midterm' or 'final'
CANVAS_MIDTERM_ASSIGNMENT_ID = ""
CANVAS_FINAL_ASSIGNMENT_ID = ""

CANVAS_DEFAULT_ASSIGNMENT_CATEGORY = "Bài tập"
DEFAULT_RESTRICTED = True

